### ISSUE TITLE
How to reference plugins

### ISSUE THREAD

**Issue by kinhunt** [axemclion/react-native-cordova-plugin#1]
Very interesting project. Tried your example, it works fine. But how can I reference third party cordova plugins. Such as :

https://github.com/parsonsmatt/WifiWizard

tried:
cordova.cordova.plugins.WifiWizard
cordova.plugins.WifiWizard
cordova.WifiWizard
cordova.navigator.WifiWizard

all undefined

**Comment by kinhunt** [comment]
it's cordova.window.WifiWizard

**Comment by axemclion** [comment]
That is correct, it basically looks at the plugin.xml for Clobbers/Merges. In Cordova, all those variables are available on window object due to [this line](https://github.com/apache/cordova-js/blob/064b25a40aab8fc2f210fdbb394d63c31e7d3e6d/src/common/init.js#L128). In react's case, there is no window, so I simply reuse the `cordova` object  to expose the APIs.
