### ISSUE TITLE
Video capture plugin??

### ISSUE THREAD

**Issue by faceyspacey** [axemclion/react-native-cordova-plugin#17]
Android React Native doesn't have a video recording package yet. Has anyone been able to get video capture to work on android using this? I'd give it a try, but I've only done iOS React native work thus far. 

Here's currently the only option for video recording on React Native iOS:

https://github.com/maxs15/react-native-screcorder

Here's the main video recording cordova plugin:

https://github.com/EddyVerbruggen/VideoCapturePlus-PhoneGap-Plugin

Incidentally I used and contributed to it 2 years ago, but it seems possibly Android cordova developers are using a built-in video capture plugin now: http://docs.phonegap.com/en/2.2.0/cordova_media_capture_capture.md.html 

Either way, anyone have any luck getting one of these 2 video capture plugins to work using react-native-cordova-plugin?

**Comment by axemclion** [comment]
@faceyspacey I just published 1.0.0 version of this plugin on npm. I also now have an [example app](https://github.com/axemclion/react-native-cordova-plugin/tree/examples) that shows how to use the plugins. While I don't have an example of the camera plugin yet, it should work.

**Comment by faceyspacey** [comment]
cool, i'll check it out soon. Finishing up an iOS app that I'll need to make an Android version for, which will require the cordova video capture plugin.

**Comment by axemclion** [comment]
@faceyspacey I just [added](https://github.com/axemclion/react-native-cordova-plugin/commit/efe79e588d7ecae600abf32c4fceb8240b7fc111) the `cordova-plugin-media-capture` in the example app and I do see Audio and Video capture working. 

Closing this issue, since it is working. Please do re-open if you run into issues.
You could also check out the working example app on appetize.io -  https://appetize.io/app/mh5mq9yvxhjpqck799jzw6t994?device=nexus5&scale=75&orientation=portrait&osVersion=6.0
