### ISSUE TITLE
cordova.exec is not a function

### ISSUE THREAD

**Issue by kinhunt** [axemclion/react-native-cordova-plugin#2]
Trying with https://github.com/parsonsmatt/WifiWizard

```
cordova.window.WifiWizard.startScan(log('success'), log('fail'));
```

gives me this error:
cordova.exec is not a function

**Comment by kinhunt** [comment]
Problem doesn't seem to be solved. Error exists

**Comment by axemclion** [comment]
@kinhunt What is the error that you see now ? Note that the adapter does not yet work with events and channels.

**Comment by kinhunt** [comment]
```
Error: cordova.exec is not a function
 stack: 
  Object.cordova.define.WifiWizard.startScan                            index.android.bun…:53768
  Object.React.createClass.getPlugins.ds.cloneWithRows.fn [as onPress]  index.android.bun…:1497
  React.createClass.touchableHandlePress                                index.android.bun…:42154
  TouchableMixin._performSideEffectsForTransition                       index.android.bun…:25822
  TouchableMixin._receiveSignal                                         index.android.bun…:25740
  TouchableMixin.touchableHandleResponderRelease                        index.android.bun…:25543
  executeDispatch                                                       index.android.bun…:15449
  forEachEventDispatch                                                  index.android.bun…:15437
  Object.executeDispatchesInOrder                                       index.android.bun…:15458
  executeDispatchesAndRelease                                           index.android.bun…:14811
 URL: undefined
 line: undefined
 message: cordova.exec is not a function
```

**Comment by axemclion** [comment]
You may have to remove and re-add the plugin. The best way to check if it works it to look for a `cordova.exec=` line in the file generated at **projectRoot\node_modules\react-native-plugin-adapter\platforms\android\cordova.js**

**Comment by kinhunt** [comment]
@axemclion thanks.

I removed the module and reinstall it with the latest version.

It gives me 'cordova.init is not a function' err. Also, there is only one AndroidManifest.xml file under  projectRoot\node_modules\react-native-cordova-plugin\platforms\android

No other files generated

update: tried with a new project, same result

**Comment by kaicherry** [comment]
I can confirm what @kinhunt is saying...simply adding  
var cordova = require('react-native-cordova-plugin');

to the default hello world after getting everything installed and built throws this error.

**Comment by axemclion** [comment]
Here is how the adapter works. When it is installed as a **node_modules** it only has a **projectRoot\node_modules\react-native-cordova-plugin\platforms\android\AndroidManifest.xml** file. This is the case when no plugin is added. This file exists so that the reactNative app compiles.

Now when you add a plugin, the platforms folder has multiple files generated. What happens here is that the plugin is downloaded from npm. The Java sources are moved to the **src** folder, the plugin's Javascript moved to **assets/www** folder. Finally, the adapter combines all the plugin's javascript together into a cordova.js file, which is included by doing require('react-native-cordova-plugin'). 

@kinhunt You are saying that a Cordova.js does not exist ? That should actually throw an error due to [this line](https://github.com/axemclion/react-native-cordova-plugin/blob/725e26f3a305385776b3cfbd9e5a96619840e535/lib/index.js#L6).

I also added a new command called repair, to just generate the cordova.js. Can you run `node_modules\.bin\cordova-plugin repair` and see if that works ? If nothing works, is there a way you could share a zip of your project and I can take a look at it ?

**Comment by kinhunt** [comment]
@axemclion thx
installing new plugin fixes the problem.
I also tried to delete cordova.js and use 'cordova-plugin repair' to generate a new one. it works.
wonderful

**Comment by axemclion** [comment]
Awesome !! Now that the code fixes this problem, do you think new users will continue hitting this issue ? Also, I would love to see your index.android.js with the wifi plugin working !!

**Comment by kinhunt** [comment]
@axemclion I do think some new users will hit this issue. I didn't do much with the wifi plugin yet. Followed your example and see if it is working or not.

```
 {
            name: 'Get wifi',
            fn: function () {
                cordova.window.WifiWizard.startScan(log('success'), log('fail'));
            }
        }, {
            name: 'Get wifi results',
            fn: function () {
                cordova.window.WifiWizard.getScanResults({numLevels: false}, log('success'), log('fail'));
            }
        }
```

and it woks. yeah~
